### ISSUE TITLE
Chapter 5: Mocha and Chai Cross-Page Testing Issue

### ISSUE THREAD

**Issue by codingdaddy** [EthanRBrown/web-development-with-node-and-express#11]
Hi, Ethan

I am really enjoying your book.
Great work!

I have written the code myself and I also have checked out your repo(ch07 tag).
I have a problem with cross page testing.
The first test always fails.
Please see the screen shot.

![screen shot 2014-11-28 at 10 01 14 am](https://cloud.githubusercontent.com/assets/3060364/5222723/8a814d64-76e5-11e4-80db-819928085e16.png)

**Comment by evolvingtech** [comment]
I had the exact same problem. It seems to stem from the fact that main.handlebars was originally very simple. As I followed the repository content, when going from git tag 'ch07' to 'ch08' there is a sudden quantum jump in code complexity for main.handlebars.

The original main.handlebars was something like:

https://gist.github.com/evolvingtech/4335333f727d00838e14

The code for main.handlebars when checking out 'ch08' jumps from 28 lines to about 68 lines. The site seems to work okay, but the cross page tests fail miserably, the same as described in this issue. For some reason

`assert(browser.field('referrer').value === referrer);`

the zombie browser.field('referrer').value doesn't end up matching with referrer.

I reworked the "broken" main.handlebars, keeping the all the stuff like bootstrap that was suddenly added in. I ignored the legacy Internet Explorer stuff. The resulting code can be found in the following gist:

https://gist.github.com/evolvingtech/18893351c6356e302c74 

I have not progressed past Ch 8 in terms of following the book code comprehensively. But at least this solved the same problem identified within this issue.

`mocha -u tdd -R spec qa/tests-crosspage.js 2>/dev/null` works fine, as does grunt.

**Comment by esanz91** [comment]
Hi Ethan,

First, I'd like to mention that I'm currently learning Node and Express and your book is great! Thank you! Once I got to Chapter 5, I got stuck (similar to OP's problem). The only suggestion I have for the future is to specify the version of the module your using at the time in the book, too, because I ran the npm install commands in the book verbatim and I guess I ended up installing the latest version of node, express, mocha, chai, and zombie, and I faced errors which I couldn't figure out until I looked at the package.json file on your Github for this book. It would have saved me a few hours (as a newbie) if the npm install commands in the book referred to the versions you were using at the time you wrote it. For example, instead of telling the readers to run "npm install --save-dev mocha", it would have been helpful to have suggested "npm install --save-dev mocha@1.20.1," because updates happen all the time and causes headaches. It's best to be on the same page.

For anyone who got stuck on Chapter 5 (like I did) with installing Mocha, Chai, or Zombie, I hope you all make sure you're running the same versions as the package.json given in this github account!

**Comment by EthanRBrown** [comment]
I want to apologize to everyone for not being more on top of these questions; between a full-time job, a part-time master's program, and working on another book, I fear that WDNE questions have taken a back burner.  Thanks to everyone who's chipped in and helped figure things out, and yes, in the next edition of the book, I plan to _specify_ package version numbers, both in the text and in the repo...because most of the problems that people have run into have stemmed from changing dependency behavior.  Sadly, many of the details in the book are already in need of a refresh, and I don't think I will have any bandwidth to do that until later this year.  When I allocated time for this book, I didn't anticipate the _after_ publication care!  Lesson learned....

**Comment by imrek** [comment]
That tests-crosspage.js really has issues. 

```javascript
assert(browser.field('referrer').value === referrer);
```

This gives me "Unspecified AssertionError", so I changed it into 
```javascript
assert.equal(browser.field('referrer').value, referrer, "Error value and referrer not matching");
```

Which again shows that browser.field('referrer').value is empty, though the field is actually populated with the URL if I change the input type from hidden to text of that field. 

It's a pitty that these bugs are left to be fixed by the reader, because this way hundreds or thousands are making the same efforts trying to resolve these on their own instead of having an updated code base that reflects fixes.

**Comment by EthanRBrown** [comment]
All issues with the cross-page tests have been fixed in the repository refactoring.  I verified that they all function correctly on Linux & OSX.  Check out either master, or the latest version (1.5.1).

**Comment by imrek** [comment]
Unfortunatelly, not for me (Linux). 
In https://github.com/EthanRBrown/web-development-with-node-and-express/blob/master/ch05/qa/tests-crosspage.js#L17 the browser.field('referrer').value is empty, that is what makes the test fail.

**Comment by EthanRBrown** [comment]
@imrek, you are correct; the tests were not passing for ch05 and ch06.  It's a regression, and I don't know how that happened...I went through and tested all the chapters before creating the 1.5 tag, so I'm not sure how this slipped by me.  The problem was that the `section` Handlebars helper was missing.  I added that and verified all the tests pass for ch05 and ch06.  I've also updated the 1.5.1 tag.  I apologize for the inconvenience, and thank you for bringing this to my attention.  Please update your repo, and try again.

**Comment by krisb1220** [comment]
Ethan, 

This issue still arises, even with the code in the repo. This code fixed the issue. 

```javascript
var Browser = require('zombie'), assert = require('chai').assert;
var browser;
suite('Cross-Page Tests', function(){
  setup(function(){
    browser = new Browser();
  });
  test('requesting a group rate quote from the hood river tour page' + 'should populate the referrer field', function(done){
    var referrer = 'http://localhost:3000/tours/hood-river';
      browser.visit(referrer, function(){
        browser.link('.requestGroupRate', function(){
          assert(browser.referrer === referrer);
          done();
        });
      });
      done();
  });
  test('requesting a group rate from the oregon coast tour page should ' + 'populate the referrer field', function(done){
    var referrer = 'http://localhost:3000/tours/oregon-coast';
    browser.visit(referrer, function(){
      browser.link('.requestGroupRate', function(){
        console.log(referrer);
        done();
      });
    });
    done();
  });

  test('visiting the "request group rate" page directly should result ' + 'in an empty referrer field', function(done){
    browser.visit('http://localhost:3000/tours/request-group-rate', function(){
      assert(browser.referrer == null)
      done();
    });
    done();
  });
});
```

**Comment by krisb1220** [comment]
Issues: 

- `browser.field('referrer').value` has been deprecated and changed to `browser.referrer`
- `browser.clickLink()` has been deprecated and changed to `browser.link()`
- You must put `done()` at the end of all tests due to their async nature

**Comment by JonathonMurphy** [comment]
A slight correction to the solution posted above. done() does not need to be called twice in a test, and clickLink() has not been deprecated. The code below will resolve the initial issue, and will fail appropriately when a page does not exist, as is the case with /tours/oregon-coast before it is created in the book. 

```
const Browser = require('zombie'),
      assert = require('chai').assert;

let browser;

suite('Cross-Page Tests', function(){
  setup(function(){
    browser = new Browser();
  });

  test('requesting a group rate quote from the hood river tour page' +
  'should populate the referrer field', function(done){
    const referrer = 'http://localhost:3000/tours/hood-river';
      browser.visit(referrer, function(){
        browser.clickLink('.requestGroupRate', function(){
          assert(browser.referrer === referrer);
        });
        done()
      });
  });

  test('requesting a group rate from the oregon coast tour page should ' +
  'populate the referrer field', function(done){
    const referrer = 'http://localhost:3000/tours/oregon-coast';
    browser.visit(referrer, function(){
      browser.clickLink('.requestGroupRate', function(){
        assert(browser.referrer === referrer);
      });
      done()
    });
  });

  test('visiting the "request group rate" page directly should result ' +
  'in an empty referrer field', function(done){
    browser.visit('http://localhost:3000/tours/request-group-rate', function(){
      assert(browser.referer == null);
    });
    done();
  });
});
```
