### ISSUE TITLE
Chapter 5: Functional Testing Errors

### ISSUE THREAD

**Issue by SisypheanPivot** [EthanRBrown/web-development-with-node-and-express#64]
Hey Ethan, 

First want to say that I'm really enjoying working through your book. I've wanted to learn Node and Express for awhile, I this is the right book for me. 

However, I'm having some issues with the Cross-page tests in Chapter 5. I've seen a few people post about these tests, but I haven't been able to find out what I'm doing wrong. I've been poring over the docs for Zombie, but they've failed to spotlight the problem so far. 

I'm receiving this error for both the hood-river and oregon-coast tests. It looks like browser.field('referrer').value is returning null and I can't figure out why. I've been stuck on this for a bit and I may just skip it for now, but I thought I'd reach out. 

Thanks.

Error

```
1) Cross-Page Tests requesting a group rate quote from the hood river tour page should populate the hidden referrer field correctly:
     Uncaught AssertionError: Unspecified AssertionError
      at qa/tests-crosspage.js:17:5
      at EventLoop.done (node_modules/zombie/lib/eventloop.js:589:11)
      at Immediate._onImmediate (node_modules/zombie/lib/eventloop.js:688:71)
```

Relevant views

```
<h1>Hood River Tour</h1>
<a class="requestGroupRate" href="/tours/request-group-rate">Request Group Rate.</a>






<h1>Request Group rate</h1>
<form>
    <input type="hidden" name="referrer">
    Name: <input type="text" id="fieldName" name="name"><br>
    Group Size: <input type="text" name="groupSize"><br>
    Email: <input type="email" name="email"><br>
    <input type="submit" value="Submit">
</form>
<script>
    $(document).ready(function() {
        $('input[name="referrer"]').val(document.referrer);
    });
</script>
```

Cross-page test file. 
```
var Browser = require('zombie'),
	assert = require('chai').assert;

var browser;

suite('Cross-Page Tests', function(){

	setup(function(){
		browser = new Browser();
	});

	test('requesting a group rate quote from the hood river tour page should ' +
			'populate the hidden referrer field correctly', function(done){
		var referrer = 'http://localhost:3000/tours/hood-river';
		browser.visit(referrer, function(){
			browser.clickLink('.requestGroupRate', function(){
				assert(browser.field('referrer').value === referrer);
				done();
			});
		});
	});

	test('requesting a group rate from the oregon coast tour page should ' +
			'populate the hidden referrer field correctly', function(done){
		var referrer = 'http://localhost:3000/tours/oregon-coast';
		browser.visit(referrer, function(){
			browser.clickLink('.requestGroupRate', function(){
				assert(browser.field('referrer').value === referrer);
				done();
			});
		});
	});

	test('visiting the "request group rate" page dirctly should result ' +
			'in an empty value for the referrer field', function(done){
		browser.visit('http://localhost:3000/tours/request-group-rate', function(){
			assert(browser.field('referrer').value === '');
			done();
		});
	});

});
```

package.json 
```
{
  "name": "meadowlark",
  "version": "1.0.0",
  "description": "A demo app made in Node with Express",
  "main": "meadowlark.js",
  "scripts": {
    "test": "test"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/SisypheanPivot/meadowlark.git"
  },
  "keywords": [
    "demo",
    "travel"
  ],
  "author": "Nicholas Dowling",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/SisypheanPivot/meadowlark/issues"
  },
  "homepage": "https://github.com/SisypheanPivot/meadowlark#readme",
  "dependencies": {
    "express": "^4.13.4",
    "express3-handlebars": "^0.5.2"
  },
  "devDependencies": {
    "chai": "^3.5.0",
    "mocha": "^2.4.5",
    "zombie": "^4.2.1"
  }
}
```

**Comment by SisypheanPivot** [comment]
Ha, never mind. Found a post with the same issue. Sorry for the redundant post.

**Comment by EthanRBrown** [comment]
Hi, Nick,

No problem...I know this has been a thorn in the side of many readers.  It's been so problematic, in fact, that I am recommending people simply skip the crosspage tests and move on.  In future versions of the book, I will probably mention it, but not provide instructions: it's really a QA function (and would probably be more appropriate for a dedicated book on QA).

Best,
  Ethan

**Comment by regalised** [comment]
Hey Nick/Ethan,

How did you solve this issue?

**Comment by liushun8910** [comment]
the Zombile V3.1：may be good,but the lastest version is bad .
The Zombile master version have a bug,and also have been solved,but it have not been merge to the master version .So,we are waiting.

here is the link: https://github.com/estevanmaito/zombie/commit/5584faa980efe5809312983dcbd6697088793d55

**Comment by captainjspace** [comment]
Hi:,
It's the chai assert api that seems to be excitable...

Not sure if this is the best solution but I modified the tests to be  
		     if (browser.field('referrer').value !== referrer)
			 assert('referrer from hood river tour page required');
and that seems work fine.  I checked by removing the hidden field from request-group-rate.handlebars, and also removing the changing the name of the field.  I can get passes and fails now.

I don't think that is effective use of the chai library though as the assert API should handle the conditional assertion rather than just asserting at all times.  I would dig into chai but I need move through the rest of the book now...

Regards,
Josh

**Comment by EthanRBrown** [comment]
@captainjspace thanks for pointing that out...I would not have thought to look at Chai for the source of the problem!  I probably won't be using Chai at all for the next edition....

**Comment by richcfml** [comment]
Thank you captainjspace. I am running Zombie v4.2.1 and the issue still there, well since it is chai it may not matter much, but thanks for the tip. That solve my problem as well.

**Comment by DemisIt** [comment]
That solve  problem: assert(browser.resources[0].request.headers._headers[0][1] === referrer);
http://stackoverflow.com/a/35952530

**Comment by devviua** [comment]
Hi,
that's can be done without chai:
`browser.assert.element('form input[name=referrer]', referrer);`
this line use only zombie.js but it slow (2 passing = 493ms).

Thank You, Ethan, at the moment enjoy your book.

**Comment by SETTER2013** [comment]
Excellent book!
Zombie in error not yours.
Two days spent on correcting errors, but went here and there it is saved:
https://github.com/estevanmaito/zombie/commit/5584faa980efe5809312983dcbd6697088793d55
During this time, I learned to understand the tests, thank you. 
Mistakes are even useful! 
MEAN taxis!

**Comment by LonelyWolfLee** [comment]
Hi, Ethan.

Version if zombie.js is '5.0.7' and still have the issue.

and also @ghost 's solution have a problem.
> browser.assert.element('form input[name=referrer]', referrer);

This will pass anyway, no matter what 'referrer' have.

Even this also pass the test
> browser.assert.element('form input[name=referrer]', 'no meaning string');

So, I'm following to your recommendation.
> I am recommending people simply skip the crosspage tests and move on.

Thank you for this excellent book.
